"""Add constraint to section_dictionary model

Revision ID: 990ad2e4e3bf
Revises: e32987ac3af9
Create Date: 2025-04-04 02:01:29.469775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990ad2e4e3bf'
down_revision: Union[str, None] = 'e32987ac3af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dictionaries', 'language',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('EN', name='languagechoice'),
               existing_nullable=False)
    op.create_unique_constraint('uix_section_dictionary', 'section_dictionaries', ['section_id', 'dictionary_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_section_dictionary', 'section_dictionaries', type_='unique')
    op.alter_column('dictionaries', 'language',
               existing_type=sa.Enum('EN', name='languagechoice'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
